version: '3.2'
services:
  app:
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - '80:80'
    volumes:
      - ./app/static/images/:/usr/share/nginx/html/images
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data