version: '3.2'
services:
  tests:
    build:
      context: ./
      dockerfile: ./app/tests/Dockerfile
    depends_on:
      postgres_test:
        condition: service_healthy
    networks:
      - my

  app:
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - '80:80'
    volumes:
      - ./app/static/images/:/usr/share/nginx/html/images
      - ./logs/:/app/logs/
    depends_on:
      - postgres
    networks:
      - my

  postgres_test:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD", "/usr/bin/pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 10s
      retries: 2
    ports:
      - '6000:5432'
    networks:
      - my

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    networks:
      - my

networks:
  my:
    driver: bridge